// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.21.0";

// src/lib/mcp/tools/list-products.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.21.0";
import { z } from "npm:zod@^3.23.8";
function supabaseForUser(ctx) {
  return createClient(
    globalThis.process.env.SUPABASE_URL,
    globalThis.process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_products_default = defineTool({
  name: "list_products",
  title: "List products",
  description: "List products from the shop's catalog. Optionally filter by a search term matched against product name and description.",
  inputSchema: {
    search: z.string().trim().optional().describe("Optional search term matched against name/description."),
    limit: z.number().int().positive().optional().describe("Max rows to return (defaults to 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "Not authenticated" }],
        isError: true
      };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("products").select("*").limit(limit ?? 20);
    if (search && search.length > 0) {
      query = query.or(`name.ilike.%${search}%,description.ilike.%${search}%`);
    }
    const { data, error } = await query;
    if (error) {
      return {
        content: [{ type: "text", text: error.message }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ygwundwdaqtmojmlwpsw";
var mcp_default = defineMcp({
  name: "computer-shop-mcp",
  title: "Computer Shop MCP",
  version: "0.1.0",
  instructions: "Tools for the computer shop. Use `list_products` to search and read the catalog as the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_products_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.21.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
